name: github page

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.5 #checkout the current branch
      - uses: peaceiris/actions-hugo@v2.5.0 #setup hugo
      - run: hugo --minify #generate static files to public directory
      - uses: peaceiris/actions-gh-pages@v3.8.0 #if push to main branch only push public directory to configured destination
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }} #use secret configuration key named PERSONAL_TOKEN
          external_repository: kusnaditjung/kusnaditjung.github.io
          publish_dir: ./public      
          publish_branch: main
          destination_dir: ./
          force_orphan: true
